name: Auto Click Ads

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次（UTC时间）
  workflow_dispatch:       # 支持手动触发

jobs:
  run-ad-clicker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install playwright requests
          playwright install chromium

      - name: Run ad clicker script
        run: python ad_clicker.py

      - name: Commit logs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}
          git add logs/*.json
          git commit -m "Update click logs $(date -u '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
